export const CIUDADES_SPAINWAY = [
  "Almería",
  "Jaén",
  "Cádiz",
  "Sevilla",
  "Córdoba",
  "Huelva",
  "Granada",
  "Málaga",
  "Andalucía",
  "Asturias",
  "Illes Balears",
  "Las Palmas",
  "Santa Cruz de Tenerife",
  "Cantabria",
  "Girona",
  "Barcelona",
  "Lleida",
  "Tarragona",
  "Madrid",
  "Alicante",
  "Valencia",
  "Castellón",
];